# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89c28eda11c9aea67d1d95e503e609a440f16d19cf72e3b99cd8c59e1f0987d8d3cf0ea0d91ff3949d3be9823acdd958bbfb5538d9bc790a6ba45b8c81d85852

test:
  secret_key_base: 3f839e4397c4ac464fc33f0f63e34aaf44c75156677fcd86597519f6013afc7b904a644fbdead39fc6e898da97c1646e6b4e8ecc5af0aa157e1cf6f56bbbc197

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
