source "https://rubygems.org"

gem "nokogiri"
gem "httparty"
gem "pry"
gem "httpclient"
gem "activesupport"
gem "capybara"
gem "poltergeist"
gem "phantomjs", :require => "phantomjs/poltergeist"
gem "google-search"
gem "google_drive"
gem "google-api-client"
gem "mechanize"
gem "launchy"
gem "typhoeus"
gem "hashie"
gem "google_custom_search_api"
gem "whenever", :require => false
gem "sidekiq"
gem "rake"

