# GoogleCustomSearchApi::GOOGLE_API_KEY = "AIzaSyDDzhd7lRDnhjPOVyxSNmVXF2654G451pE"
# GoogleCustomSearchApi::GOOGLE_API_KEY = "AIzaSyC61_cb5U9OwHMjc31ateh5-mdxXqpLk8Y"
# GoogleCustomSearchApi::GOOGLE_API_KEY = "AIzaSyCiKBT6cQl_dVkAQTHzZ-Imitg7cv-hH3M"
# GoogleCustomSearchApi::GOOGLE_API_KEY = "AIzaSyAa3FgaIlXHtJuGxlR3DUgMxjCoRa5mAz4"
# GoogleCustomSearchApi::GOOGLE_API_KEY = "AIzaSyBsoGLdxIsIMgPSZzLkRiqb8RqcWBKb4ko"
GoogleCustomSearchApi::GOOGLE_API_KEY = "AIzaSyAqtIxLX12WgfM830WK04rsoPF_-mBhGmU"
# GoogleCustomSearchApi::GOOGLE_API_KEY = "AIzaSyD81QBaV7b4gyOmRrv3iWs2ya4a08Ls9KY"
# GoogleCustomSearchApi::GOOGLE_API_KEY = "AIzaSyASpidxuCOmPwjeaYGKgunbVchJCbdSbTk"
# GoogleCustomSearchApi::GOOGLE_API_KEY = "AIzaSyA-PKLda3V_7tL9GIsOXqXNAV_MQEvOZ6U"
GoogleCustomSearchApi::GOOGLE_SEARCH_CX =  "016010277763527429812:tqprubgay5k"

